PARD.xcodeproj/project.pbxproj
PARD/Sources/CALayerExtension.swift
PARD/Sources/HamburgerBarView.swift
PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/Home/ViewControllers/HomeViewController.swift
PARD/Sources/NSMutableAttributedStringExtension.swift
PARD/Sources/PardTextField.swift
PARD/Sources/ToastBarView.swift
PARD/Sources/TooltipView.swift
PARD/Sources/User/HomeTopView.swift
PARD/Sources/User/ViewControllers/UserInfoPolicyViewController.swift

- 홈 화면 전반적인 UI구현
- 홈 화면 tooltip 구현
- 다만 디테일 적인 디자인 부분을 수정해야함
close #45 
close #36 
<br>
- 홈화면의 전반적인 UI 및 툴팁 구현
https://github.com/Club-PARD/PARD_iOS/assets/122281984/936a60c9-f8f9-46e6-9681-8eebe7656419
<br>
구현한 부분 체크리스트
<br>
디테일한 디자인 부분 추가 수정 필요

[Feat] 홈화면 구현

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD.xcworkspace/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/Home/HomeUpcommingView.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

[Fix] detail 수정

---

PARD.xcodeproj/project.pbxproj
PARD.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/Calendar/EventTableViewCell.swift
PARD/Sources/Calendar/ViewControllers/CalendarViewController.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/Home/ViewControllers/HomeViewController.swift
PARD/Sources/PardNotionLinkView.swift
PARD/Sources/User/HomeTopView.swift
Pods/Pods.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist

close #48 
<br>
- 내 일정 페이지 구현 완료
<br>
구현한 부분 체크리스트
<br>
추가로 햄버거 바의 노션 링크도 구현했습니다!!
추가로 수정할 부분 찾았네유ㅠㅠ

[Feat] 내 일정 페이지 구현

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD.xcworkspace/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/Home/ViewControllers/MyPageViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #52 
<br>
<br>
구현한 부분 체크리스트
<br>
@mingseobi 태그 ui 수정 부탁해요 !

[Feat] mypage server data 사용

---

PARD.xcodeproj/project.pbxproj
PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/API/ScheduleController.swift
PARD/Sources/Calendar/EventTableViewCell.swift
PARD/Sources/Calendar/ViewControllers/CalendarViewController.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/PardAppModel.swift
PARD/Sources/ScheduleModel.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #54 
<br>
서버에서 일정관련 데이터를 가져왔습니다.
<br>
구현한 부분 체크리스트
<br>
@jinsejin 지난 일정과 다가오는 일정 필터링 + UI 구성 디테일 부탁해요 !

[Feat] add schedule data from server

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/User/ViewControllers/MainLoginViewController.swift
PARD/Sources/User/ViewControllers/UserInfoPolicyViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #69 
<br>
다른 사람 구글계정으로 로그인하면 그전 쿠키가 남아있는 현상 해결
dispatchQueue를 사용하여 딜레이를 줘서 데이터를 모두 불러오도록 함
<br>
구현한 부분 체크리스트
<br>

[Fix] 다른 사람 구글계정으로 로그인하면 그전 쿠키가 남아있는 현상

---

PARD/Sources/API/UserController.swift

close #71 
<br>
<br>
구현한 부분 체크리스트
<br>
- replacingOccurrences를 사용해서 앞 문자열 제거

[Feat] 서버로부터 받은 Role 데이터 중 "ROLE_" 을 제거해서 저장하기

---

PARD/Sources/MyScore/ScoreRecordsView.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift

close #40 
<br>
내 점수 화면 점수 기록 구현 완료했습니다!
구분선 + 라운드 표시 구현 완료
<br>
구현한 부분 체크리스트
<br>

[Feat] 내 점수 화면 점수 기록 구현

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/API/UserController.swift
PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/PardAppModel.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #80 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 홈 화면에 파드너십 점수 서버에서 불러오기

---

PARD.xcodeproj/project.pbxproj
PARD/Sources/API/RankController.swift
PARD/Sources/API/UserController.swift
PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/PardAppModel.swift

close #82 
<br>
<br>
구현한 부분 체크리스트
<br>
데이터 가져오면서 생긴 UI이슈 해결 부탁드려요 @mingseobi

[Feat] top 3 rank + my rank 서버 연결

---

PARD.xcodeproj/xcuserdata/mingseobi.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/Home/ViewControllers/HomeViewController.swift
PARD/Sources/Home/ViewControllers/MyPageViewController.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
Pods/Pods.xcodeproj/xcuserdata/mingseobi.xcuserdatad/xcschemes/xcschememanagement.plist

close #77 
<br>
- 네비게이션바 배경색 지정하기
- title 색상 변경하기
<br>
구현한 부분 체크리스트
<br>

[Feat] 네비게이션바 배경색 지정하기 + title 색 지정

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/API/RankController.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift
PARD/Sources/PardAppModel.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close 
<br>
<br>
구현한 부분 체크리스트
<br>
@mingseobi 불러온 데이터 화면에 넣어주세요 !

[Feat] get total rank

---

PARD.xcodeproj/project.pbxproj
PARD.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/+Font.swift
PARD/Sources/Calendar/EventTableViewCell.swift
PARD/Sources/Calendar/ViewControllers/CalendarViewController.swift
PARD/Sources/HamburgerBarViewController.swift
PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/Home/ViewControllers/HomeViewController.swift
PARD/Sources/Home/ViewControllers/MyPageViewController.swift
PARD/Sources/MyScore/ScoreRecordsView.swift
PARD/Sources/MyScore/ToolTIpViewInMyScore.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift
PARD/Sources/UITabBarController.swift
PARD/Sources/User/HomeTopView.swift

close #89 
close #92 
전체적으로 화면 전환시 생기는 탭바 활성화/비활성화 구현
<br>
https://github.com/Club-PARD/PARD_iOS/assets/122281984/9fb33d14-4e92-4645-9732-86b454a6e7e9
<br>
구현한 부분 체크리스트
<br>
myScoreViewController의 tooltip Class를 다른 페이지로 옮겨뒀습니다.

[Fix] 전체적으로 화면 전환시 생기는 탭바 활성화/비활성화 및 네비게이션 색 수정

---

PARD.xcodeproj/project.pbxproj
PARD/Sources/+Font.swift
PARD/Sources/API/RankController.swift
PARD/Sources/Calendar/EventTableViewCell.swift
PARD/Sources/Calendar/ViewControllers/CalendarViewController.swift
PARD/Sources/HamburgerBarView.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift
PARD/Sources/NSMutableAttributedStringExtension.swift
PARD/Sources/PardNotionLinkView.swift
PARD/Sources/TooltipView.swift
PARD/Sources/UIColor.swift
PARD/Sources/User/HomeTopView.swift
PARD/Sources/User/ViewControllers/MainLoginViewController.swift
PARD/Sources/User/ViewControllers/UserAuthenticationViewController.swift

close #
<br>
https://github.com/Club-PARD/PARD_iOS/assets/122281984/8e99f47b-158a-4f59-8923-61d2877f726e
<br>
구현한 부분 체크리스트
<br>

[Fix] 그라데이션 색상 구현 및 적용

---

PARD.xcodeproj/project.pbxproj
PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/App/SceneDelegate.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift
PARD/Sources/User/AppleLogin/GoogleLoginManager.swift
PARD/Sources/User/ViewControllers/MainLoginViewController.swift
PARD/SplashViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #100 
<br>
<br>
구현한 부분 체크리스트
<br>

[Feat] splash 화면에 로그인 여부에 따라 다른 화면 연결하기

---

PARD/SplashViewController.swift

close #102 
<br>
<br>
구현한 부분 체크리스트
<br>

[Feat] add splash view

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/API/UserController.swift
PARD/Sources/App/SceneDelegate.swift
PARD/Sources/Home/ViewControllers/MyPageViewController.swift
PARD/Sources/PardAppModel.swift
PARD/Sources/User/AppleLogin/GoogleLoginManager.swift
PARD/SplashViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #104 
<br>
쿠키 만료 대비를 위한 자동로그인
- 최초 로그인이 아닌 경우, 처음 앱 진입 시 데이터 불러옴
<br>
구현한 부분 체크리스트
<br>

[fix] cookie 만료를 방지하기 위한 자동로그인 구현

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift

close #106 
<br>
로그아웃 기능 구현하기
<br>
구현한 부분 체크리스트
<br>
- 추후 팝업 모달과 연결 필요

[Feat] 로그아웃 기능

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/Home/ViewControllers/MyPageViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #129
<br>
로그아웃 후 로그인화면 이동 & UserDefaults 데이터 삭제
https://github.com/user-attachments/assets/c6029288-c49f-4f69-8d88-17721f7d1716
https://github.com/user-attachments/assets/a3bf3a7e-48bd-496e-9f21-3939875b27df
<br>
구현한 부분 체크리스트
<br>

[Fix] 로그아웃 후 로그인 화면 이동 & UserDefaults 데이터 초기화

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/API/UserController.swift
PARD/Sources/Home/ViewControllers/MyPageViewController.swift
PARD/Sources/NSMutableAttributedStringExtension.swift
PARD/Sources/UILabelExtension.swift
PARD/Sources/User/HomeTopView.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #143 
<br>
탈퇴 후 탈퇴한 계정으로 로그인 시
<br>
구현한 부분 체크리스트
<br>
탈퇴하기 후 탈퇴한 계정으로 로그인 시, 사용자명이 '하나'로 나오는지까지 확인 완료

[Fix] 탈퇴하기 함수 연결 및 서버 연결 & 홈화면, 마이페이지화면 줄간격 수정

---

PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift

close #147 
<br>
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] user의 랭킹 불러오는 코드 수정

---

PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
PARD/Sources/API/ScheduleController.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/Home/ViewControllers/HomeViewController.swift

close #151
<br>
홈화면의 UPCOMMING EVENT 데이터가 서버에서 불러온 내용이 아니라 고정되어 있는 현상을 수정
<br>
구현한 부분 체크리스트
<br>
현장 장소가 "" 비어 있어서 비어있을 시 장소 표시 안되게 만들었습니다.

[fix]홈화면의 UPCOMMING EVENT 데이터가 서버에서 불러온 내용이 아니라 고정되어 있는 현상 수정

---

PARD.xcodeproj/project.pbxproj
PARD.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/User/ViewControllers/UserInfoPolicyViewController.swift
PARD/Sources/User/nextBottomButton.swift
Pods/Pods.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist

close #153  
https://github.com/user-attachments/assets/994388ec-e010-4492-a4d6-70fc2418a661
- 
<br>
- 이용약관 페이지에서 버튼 색상 그라데이션 추가 및 체크 여부에 따라 버튼 활성화 및 비활성화 수정
<br>
구현한 부분 체크리스트
<br>

[Fix] 이용약관 페이지에서 버튼 색상 그라데이션 추가 및 체크 여부에 따라 버튼 활성화 및 비활성화 수정 및 폰트 적용 

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift

close #157 
<br>
- 마이페이지 내정보 칩 크기 조절
<br>
구현한 부분 체크리스트
<br>

[Fix] 마이페이지 내정보 칩 크기 조절

---

PARD/Sources/Home/ViewControllers/HomeViewController.swift
PARD/Sources/PopUpModal/Views/PopUpModalView.swift
PARD/Sources/User/ViewControllers/UserInfoPolicyViewController.swift
Pods/Pods.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist

close #
<br>
- 모달 창 레이아웃 수정
<br>
구현한 부분 체크리스트
<br>

[Fix] 모달창 레이아웃 수정

---

PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/PardAppModel.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #161 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 홈은 0점, 더보기 페이지에서는 0.0점 -> 형식 통일하기(불러오는 방식 통일하기)

---

PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift

close #180 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 타이포 수정

---

PARD.xcodeproj/project.pbxproj
PARD.xcodeproj/xcshareddata/xcschemes/PARD.xcscheme
PARD.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/API/RankController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #185 
<br>
rank top3와 total rank 데이터 불러오는 부분을 수정하였습니다.
<br>
구현한 부분 체크리스트
<br>
- 서버 요청 시 사용자의 기수 데이터 보내기

[Fix] 서버 요청에 따라 generation 보내기

---

PARD/Sources/API/RankController.swift
PARD/Sources/App/SceneDelegate.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #187 
<br>
<br>
구현한 부분 체크리스트
<br>
최초 로그인 시 파드너십 더보기에서 사용자의 랭킹 현황이 보이지 않는 현상 해결

[Fix] 최초 로그인 시 파드너십 더보기에서 사용자의 랭킹 현황이 보이지 않는 현상 해결

---

PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift

close #
https://github.com/user-attachments/assets/87105f6e-91b6-443c-8a7c-d8dfad71b60c
<br>
[Fix] 탭바 높이 유동적으로 만들기 + 내 점수 페이지 스크롤 가능하게 만들기
<br>
구현한 부분 체크리스트
<br>

[Fix] 탭바 높이 유동적으로 만들기 + 내 점수 페이지 스크롤 가능하게 만들기

---

PARD.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
PARD/Sources/API/ReasonController.swift
PARD/Sources/MyScore/ScoreRecordCell.swift
PARD/Sources/MyScore/ScoreRecordsView.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/PardAppModel.swift

close #192 
<br>
점수기록 title과 content 위치 확인 필요
<br>
구현한 부분 체크리스트
<br>

[fix] 점수기록 title과 content 위치 확인 필요

---

PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist
PARD/Sources/API/RankController.swift
PARD/Sources/API/ReasonController.swift
PARD/Sources/API/ScheduleController.swift
PARD/Sources/API/UserController.swift
PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/MyScore/ScoreRecordCell.swift
PARD/Sources/MyScore/ScoreRecordsView.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/UILabelExtension.swift
PARD/Sources/User/ViewControllers/UserInfoPolicyViewController.swift
Pods/Pods.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist

close #179 
<br>
최초 로그인 시 점수기록 데이터가 보이지 않는 현상 해결
https://github.com/user-attachments/assets/7774e2f4-692e-4972-a764-c7cc8c87fe05
등록되지 않은 회원인 경우 - 내점수 페이지
https://github.com/user-attachments/assets/10351a61-eafb-4d82-82e1-99d9921336fd
등록된 회원인 경우 - 내점수 페이지
https://github.com/user-attachments/assets/2a86cedc-4bc4-4368-9e9d-eea604351987
<br>
구현한 부분 체크리스트
<br>

[fix] 최초 로그인 시 점수기록 데이터가 보이지 않는 현상 해결

---

PARD/Sources/User/ViewControllers/MainLoginViewController.swift
PARD/SplashViewController.swift

close #201 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] background color 수정

---

PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift

close #206 
<br>
점수 기록 툴팁 포커스 아웃 범위 수정하였습니다.
<br>
구현한 부분 체크리스트
<br>

[Fix] 점수 기록_툴팁 포커스 아웃 범위 수정

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift

close #204 
<br>
마이페이지_버튼 클릭 범위 수정 완료 하였습니다.
src="https://github.com/user-attachments/assets/31d89120-e9ed-41fc-a080-9cae97ec2e05">
<br>
구현한 부분 체크리스트
<br>

[Fix] 마이페이지_버튼 클릭 범위 수정

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift

close #212 
<br>
마이페이지_버튼 클릭 범위 재수정 완료 하였습니다.
src="https://github.com/user-attachments/assets/31d89120-e9ed-41fc-a080-9cae97ec2e05">
<br>
구현한 부분 체크리스트
<br>

[Fix] MypageVC Button Click range Update

---

PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift

close #231 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 점수정책 페이지 띄어쓰기 적용

---

PARD/Sources/HamBurgerTableViewCell.swift

close #223 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 햄버거바_노션 아이콘 정렬

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift

close #226 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 마이페이지_상단배너 + 토글 버튼 수정

---

PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
Pods/Pods.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist

close #219 
<br>
<br>
구현한 부분 체크리스트
<br>

[fix] 탭바 높이 재설정

---

PARD/Sources/MyScore/ScoreRecordsView.swift

close #225 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 점수 기록_UI 수정

---

PARD/Sources/HamBurgerTableViewCell.swift

close #222 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 햄버거바_세미나 구글폼+공식채널 link 연결

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift

close #243 
<br>
마이페이지 화면 스크롤 추가
<br>
구현한 부분 체크리스트
<br>
평상시에는 스크롤 불가능하고 만약 화면 넘어갈 경우 스크롤 됩니다

[Feat] 마이페이지 화면 스크롤 추가

---

PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #227 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] qr 이동시 겹쳐보이는 현상 해결

---

PARD/Sources/API/QrController.swift

close #246 
<br>
https://github.com/user-attachments/assets/a6d07c3a-df72-4fa4-9e6b-19177daf2fd1
<br>
구현한 부분 체크리스트
<br>

[Fix] QR_모달이 뜨고나서 안사라지는 문제 해결

---

PARD/Sources/HamBurgerTableViewCell.swift
PARD/Sources/HamburgerBarView.swift
PARD/Sources/PardNotionLinkCollectionViewCell.swift
PARD/Sources/PardNotionLinkView.swift

close #249 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 햄버거바_폰트 두께 및 사이즈 수정

---

PARD/Sources/API/RankController.swift
PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/Home/ViewControllers/HomeViewController.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #251 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 어드민 점수표시 수정

---

PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift

close #260 
<br>
<br>
구현한 부분 체크리스트
<br>

[fix]홈화면/일정 동기화 안되는 문제 해결

---

PARD/Sources/API/ScheduleController.swift
PARD/Sources/ScheduleModel.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #268 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 일정에서 '파트' 문자열 제거

---

PARD/Sources/HamBurgerTableViewCell.swift
PARD/Sources/HamburgerBarView.swift

close #272 
<br>
햄버거바_노션 셀 클릭 시 셀 업데이트
<br>
구현한 부분 체크리스트
- 
<br>

[Fix] 햄버거바_노션 셀 클릭 시 셀 업데이트

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift
PARD/Sources/User/HomeTopView.swift

close #270 
<br>
<br>
구현한 부분 체크리스트
<br>

[fix] 홈 화면 칩 오토레이아웃 수정

---

PARD/Sources/MyScore/RankingTableViewCell.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift

close #274 
<br>
<br>
구현한 부분 체크리스트
<br>

[Fix] 전체랭킹_UI_테이블뷰 하단 라운드 처리

---

PARD/Sources/MyScore/ScoreRecordsView.swift
PARD/Sources/User/HomeTopView.swift

close #278 
<br>
내점수 기록 - 최근 사건들을 앞열에 보이게 하기
<br>
구현한 부분 체크리스트
<br>

[fix] 내점수 기록 - 최근 사건들을 앞열에 보이게 하기

---

PARD.xcodeproj/project.pbxproj
PARD/Sources/API/ScheduleController.swift
PARD/Sources/Calendar/ViewControllers/CalendarViewController.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/MyScore/RankingTableViewCell.swift
PARD/Sources/MyScore/ScoreRecordsView.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift
PARD/Sources/User/HomeTopView.swift
Pods/Pods.xcodeproj/xcuserdata/ram.xcuserdatad/xcschemes/xcschememanagement.plist

close #
<br>
<br>
구현한 부분 체크리스트
<br>

[Feat] 특정 페이지 탭바 제거하기

---

PARD/Sources/Home/ViewControllers/MyPageViewController.swift

close #280 
<br>
마이페이지 라벨 UI 센터 수정
<br>
구현한 부분 체크리스트
<br>

[Fix] 마이페이지 라벨 UI 센터 수정

---

PARD/Sources/API/ScheduleController.swift

close #
<br>
<br>
구현한 부분 체크리스트
<br>

[Feat] 일정 본인파트 + 전체 일정만 가져오기

---

PARD/Sources/API/ScheduleController.swift

close #
<br>
<br>
구현한 부분 체크리스트
<br>

[Feat] 불필요 코드 삭제

---

PARD/Sources/API/RankController.swift
PARD/Sources/PardAppModel.swift

close #
<br>
<br>
구현한 부분 체크리스트
<br>

[Feat] 랭킹 받아오기 수정

---

PARD/Sources/User/HomeTopView.swift

close #
<br>
<br>
구현한 부분 체크리스트
<br>

[Feat] 팡울이 점수 + 전체전수 기준 팡울 캐릭터 업그레이드

---

PARD.xcworkspace/xcuserdata/jinsejin.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
PARD/Sources/Calendar/ViewControllers/CalendarViewController.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/Home/ViewControllers/HomeViewController.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift
PARD/Sources/MyScore/ViewControllers/RankingViewController.swift
Pods/Pods.xcodeproj/xcuserdata/jinsejin.xcuserdatad/xcschemes/xcschememanagement.plist

close #
<br>
[[fix] 탭바 - 홈화면 및 마이페이지화면 제외하고 백그라운드 갔다가 돌아올때 탭바가 다시 생기는 오류 수정]
<br>
구현한 부분 체크리스트
<br>

[fix] 탭바 - 홈화면 및 마이페이지화면 제외하고 백그라운드 갔다가 돌아올때 탭바가 다시 생기는 오류 수정

---

PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift

close #
<br>
<br>
구현한 부분 체크리스트
<br>

[fix] 탭바 높이 조절

---

PARD/Sources/User/ViewControllers/UserInfoPolicyViewController.swift

close #290 
<br>
회원인증_checkmark 탭 수정
<br>
구현한 부분 체크리스트
<br>

[Fix] 회원인증_checkmark 탭 수정

---

PARD/Sources/Calendar/ViewControllers/CalendarViewController.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/Home/ViewControllers/HomeTabBarViewController.swift
PARD/Sources/User/HomeTopView.swift
PARD/Sources/User/ViewControllers/UserInfoPolicyViewController.swift

close #
<br>
탭바 높이 수정 , HomeTopView.swift 칩 cornerRadius 12로 증가, 그라데이션 색 추가및 remainDay == 0 일 경우 UI 추가, 
<br>
구현한 부분 체크리스트
<br>

[fix] 탭바 높이 수정 , 홈화면 칩 cornerRadius 12로 증가, 그라데이션 색 추가 및 remainDay == 0 일 경우 UI 추가

---

PARD/Sources/Home/HomePardnerShipView.swift
PARD/Sources/Home/HomeUpcommingView.swift
PARD/Sources/MyScore/ViewControllers/MyScoreViewController.swift

close #293 
<br>
클릭 버튼영역 넓히기
<br>
구현한 부분 체크리스트
<br>

[Fix] 클릭 버튼영역 넓히기

---

PARD/Sources/PardNotionLinkView.swift

close #295
<br>
- 파트 링크 데이터 수정
<br>
구현한 부분 체크리스트
<br>

[Fix] PardNotionLinkView 파트 링크 데이터 수정
